### ISSUE TITLE
broken "Rewrite account names" link

### ISSUE THREAD

**Issue by lestephane** [simonmichael/hledger_site#10]
on https://hledger.org/journal.html?highlight=aliases#rewriting-accounts following the link

```md
See also [Cookbook: Rewrite account
names](https://github.com/simonmichael/hledger/wiki/Rewrite-account-names).
```
leads to the github project page for hledger

I expected a `journal.md` to be present in the top-level of this project, but couldn't find it.
Knowing where journal.md is located for the hledger master branch, i would modify it to point to

```
[Cookbook: Rewrite account
names](rewrite-account-names.html)
```

- is that correct?
- where is journal.md for master?

**Comment by simonmichael** [comment]
Thanks! I've fixed this and a few more remaining wiki links, in the dev docs but not yet in the old doc versions (1.16, 1.15 etc.)

hledger_site/journal.md (web version of the journal format reference manual) is generated from hledger/hledger-lib/hledger_journal.m4.md by `./Shake [web]manuals`. (The hledger_site repo is expected to be symlinked as `./site`.) Some related dev docs which need updating: CONTRIBUTING.md#docs, doc/README, Shake.hs.

**Comment by simonmichael** [comment]
Added a "generated by" comment at the top of those web manuals.

**Comment by lestephane** [comment]
thanks, looks great now
