### ISSUE TITLE
mdBook not converting some links properly

### ISSUE THREAD

**Issue by winterqt** [simonmichael/hledger_site#105]
According to mdBook's documentation, `.md` links [should be converted to `.html`](https://rust-lang.github.io/mdBook/format/markdown.html#links), but this does not happen on e.g. the double entry accounting link on https://hledger.org/5-minute-quick-start.html#how-do-i-use-it- -- it retains the `.md`, resulting in a 404.

Oddly enough, this does not happen on the `install.md` link, just (at least) the `accounting.md` one.

**Comment by simonmichael** [comment]
Thanks! Seems fixed now (by making it a relative url).
