### ISSUE TITLE
--host not working for web?

### ISSUE THREAD

**Issue by jungle-boogie** [simonmichael/hledger_site#109]
Hello,

hledge web -h says this:
```
--host=IPADDR          listen on this IP address (default: 127.0.0.1)
```

So I've tried that:
```
$ hledger web --host=0.0.0.0
hledger: Error: Unknown flag: --host (use -h to see usage)
$ hledger web --host 192.168.0.79
hledger: Error: Unknown flag: --host (use -h to see usage)
```

Running this version:
```
$ hledger web --version
hledger-web 1.34, linux-x86_64
```

**Comment by jungle-boogie** [comment]
I see two of my mistakes:
1. `hledger web` isn't right - it's `hledger-web`, which this will then work: `$ hledger-web --host=192.168.0.79`
2. I posted this to the wrong repo - sorry about that!

**Comment by simonmichael** [comment]
A -- is needed sometimes, https://hledger.org/dev/hledger.html#add-on-commands
