### ISSUE TITLE
search results annoyingly return one match for each hledger release

### ISSUE THREAD

**Issue by lestephane** [simonmichael/hledger_site#11]
When I search the docs, i only care about a specific version. I don't know how to select the version i'm interested in (hint: there should be an obvious one), so I just type something in the search field of hledger.org (say, `cookbook`), and here is what I see

![image](https://user-images.githubusercontent.com/5460884/70415692-e9844400-1a65-11ea-854c-9d179a766302.png)

the list is polluted with matches from previous versions

Even if one decided to keep matches from all versions, the matches have no indication of the version they relate to, this is really annoying.

**Comment by simonmichael** [comment]
Good catch, thanks. There may be something we can do in https://github.com/simonmichael/hledger_site/blob/master/conf.py.

**Comment by lestephane** [comment]
Now that there is a 'selected version' in the upper right corner, it brings us closer to constraining the search to that version. 

My understanding is that, since all versions available for selection in the upper right corner are present in sub-directories of master, and because the search engine searches master, one gets matches in all previously released versions that are still visible in master.

So it's not like the search engine searches a different git tag based on the selected version.

I don't know what the sphynx best practice is for this. Is this search capability a built-in feature of Sphynx, or are you using an extension?

**Comment by simonmichael** [comment]
I'm using sphinx's default search. Perhaps there's a way to configure it to ignore certain directories ? There's also some more complicated better-performing search extension available. 

On readthedocs, the entire doc set is versioned and switching versions means switching between git tags. Since hledger.org is a mix of versioned and unversioned docs, I have copies of all versions (of the reference manuals) in master. This creates hassles like this (also, slower build times), but is the simplest solution I could find.

**Comment by lestephane** [comment]
So excluding the non-relevant directories from search seems the path of least resistance.

Is sphynx using a full text index, or the equivalent of "grep -r"?

**Comment by simonmichael** [comment]
I'm sorry, I don't know. Would you have time to investigate ?
>

**Comment by lestephane** [comment]
I may be able to look at it at the beginning of next month, when i do my bookkeeping chores again

**Comment by simonmichael** [comment]
Fixed by #28.
