### ISSUE TITLE
Broken link in manual -- journal differences hledger and Ledger

### ISSUE THREAD

**Issue by dcrossleyau** [simonmichael/hledger_site#112]
The hledger manual has a broken link in the section https://hledger.org/1.34/hledger.html#journal
at paragraph 3:

differences and interoperation tips are described at [hledger and Ledger]

That linke to 1.34/ledger.html ... but 404.

**Comment by dcrossleyau** [comment]
Ah, i found the correct link via the draft Wikipedia article.
The Reference 2 refers to it at the main site
https://hledger.org/ledger.html
i.e. not relative to the Manual.

**Comment by simonmichael** [comment]
Thank you! Fixed.
