### ISSUE TITLE
Update docs to indicate hledger support has been added to 

### ISSUE THREAD

**Issue by thomascwells** [simonmichael/hledger_site#114]
I believe [this section of the documentation](https://github.com/simonmichael/hledger_site/blob/5960c7e2c13ecfa609338c38bea2e42cc6e5ebb4/src/paisa.md?plain=1#L62-L65) is now outdated.

I appears that hledger support is now included in paisa: https://github.com/ananthakumaran/paisa/discussions/12#discussioncomment-6018166

**Comment by simonmichael** [comment]
Thanks! I have updated that section.
