### ISSUE TITLE
Download/Install page lists command that results in error

### ISSUE THREAD

**Issue by HanKruiger** [simonmichael/hledger_site#12]
https://hledger.org/download.html mentions that I can test my installation with `hledger iadd --version`, but this results in:
```
hledger: command iadd is not recognized, run with no command to see a list
```
I'm assuming `iadd` has been renamed to `add` (as `hledger add --version` does work[^1]), but I could be wrong.

I am on macOS Catalina and I installed hledger with `brew install hledger`.

Cheers! 👋 

[^1]: However it only shows the `hledger` version, not the `hledger add` version, if that would even be a thing?

**Comment by simonmichael** [comment]
Hi.. no, [hledger-iadd](https://hackage.haskell.org/package/hledger-iadd) is an addon, shipped separately from hledger, and not currently packaged in homebrew. The hledger-install.sh script is one way to install it. Perhaps I should tweak the download page

**Comment by simonmichael** [comment]
Download page tweaked. It now links to info about add-ons, but does not otherwise mention hledger-iadd.

**Comment by simonmichael** [comment]
Re ^1: `hledger add --version` is equivalent to `hledger --version` (the `--version` flag takes priority).

**Comment by HanKruiger** [comment]
Thanks! And thanks for taking the time for developing hledger. I recently found out about it, and will probably migrate to here from GnuCash because it seems really nice!
