### ISSUE TITLE
forecasting doc could now include a `Burn Rate` or `Runway` example using --historical

### ISSUE THREAD

**Issue by lestephane** [simonmichael/hledger_site#14]
A computation that is important for business owners (especially bootstrapped entrepreneurs) is the burn rate, or rather it's complement, the runway, which is the answer to "how long can the company stay in business given the current recurring revenue and expenses".

I found the following to be useful:

```bash
hledger bal -b "today" --monthly --historical --forecast "Assets:Business"
```

Unfortunately I don't have the journal used in the existing documentation to run this query on it, but maybe you do, and show how this could help determine whether the business is a going concern, or a household can visualize when they'll enter the danger zone.

The month when the total drops below zero is the moment you're insolvent (or entering debt), and the count of month until then is how long you'd have to turn the company around or get new income, or cut expenses, or adjust budgets, or or or... very useful

**Comment by simonmichael** [comment]
Would you be interested in updating/improving this doc, or helping @adept (the original author) to do it ? I notice it says "this is for hledger 1.5" on the top.

**Comment by simonmichael** [comment]
Some other forecasting reports for the record, I think you know these: 

    hledger bs --forecast -M -b today [business]  # or -W or -D
    hledger reg --forecast -H -b today assets:business
    hledger-ui --watch --register assets:business, press F

**Comment by lestephane** [comment]
@adept do you still have the .journal you used when writing the initial doc? Maybe we can re-run the new commands against it?

**Comment by adept** [comment]
I am pretty sure that I took one of the example journals. Page says "This section uses examples/bcexample.hledger from hledger source repository" -- i would have expected this to be true

**Comment by lestephane** [comment]
I'll see if I can cook up some compelling example from journal files in the examples directory.

**Comment by simonmichael** [comment]
I'll close this unless someone wants to revive it.

**Comment by lestephane** [comment]
I can close it, since I asked for this, and I no longer see how I can do it in a simple digestible chunk.
