### ISSUE TITLE
Mistake that makes it hard for Linux newbies to install shell completion

### ISSUE THREAD

**Issue by schoettl** [simonmichael/hledger_site#17]
https://hledger.org/command-line-completion.html

- Add the command `'source ~/.hledger-completion.bash'` this to the end of your `~/.bashrc file`.

should be:

```
- Add the command `source ~/.hledger-completion.bash` to the end of your `~/.bashrc file`.
```

without the single quotes around the command. And no "this".

**Comment by simonmichael** [comment]
Thanks!
