### ISSUE TITLE
"Auto-detected account types" table broken in 1.21 docs

### ISSUE THREAD

**Issue by lubieowoce** [simonmichael/hledger_site#39]
https://hledger.org/1.21/hledger.html#auto-detected-account-types
Screenshot:
![image](https://user-images.githubusercontent.com/13698226/123157209-881a9f00-d46a-11eb-87e8-81def4e65fb2.png)

Looks like this is because mdBook uses¹ Github-flavored Markdown syntax for tables, so `|` needs to be escaped in table cells.
Syntax reference: https://github.github.com/gfm/#example-200

---

¹ This actually took a bit of digging to confirm, but [mdBook docs say](https://rust-lang.github.io/mdBook/for_developers/preprocessors.html?highlight=pulldown-cmark#hints-for-implementing-a-preprocessor) it uses the `pulldown-cmark` crate whose [readme says](https://crates.io/crates/pulldown-cmark) it accepts GFM-style tables.

**Comment by simonmichael** [comment]
Thanks for the report and PR!

This duplicates https://github.com/simonmichael/hledger/issues/1573 (understandable, since that issue was created in the main repo). I'll comment more on your PR.

**Comment by simonmichael** [comment]
PR fix was not effective, we agreed that it would make sense to apply the #1573 fix (use a literal block) to 1.21 and all old versions.

**Comment by simonmichael** [comment]
This has been done for the affected versions.
