### ISSUE TITLE
docs: "--used/--declare payees" not available

### ISSUE THREAD

**Issue by agander** [simonmichael/hledger_site#45]
These parameters are not available for version 1.21:

```
gander@toast ~/.hledger/load_from_here (master)
$ hledger --version
hledger 1.21
gander@toast ~/.hledger/load_from_here (master)
$ hledger --declare  payees
hledger: Unknown flag: --declare (use -h to see usage)
gander@toast ~/.hledger/load_from_here (master)
$ hledger --used  payees
hledger: Unknown flag: --used (use -h to see usage)
```
but are listed in the help:

```
hledger payees -h

payees [OPTIONS] [QUERY]
  List the unique payee/payer names that appear in transactions.

Flags:
     --declared                          show payees declared with payee
                                         directives
     --used                              show payees referenced by
                                         transactions

```

**Comment by agander** [comment]
@simonmichael ok to log this issue here?

**Comment by simonmichael** [comment]
Thanks for the report @agander. This sounds like an issue with the hledger CLI, so main issue tracker would be better (http://bugs.hledger.org). Also could you check it with the current release, 1.22 ?

**Comment by agander** [comment]
> PS the problem is that command-specific flags must be written after the command, 
> this is [mentioned](https://hledger.org/hledger.html#command-options) in the manual hopefully.

Indeed, sorry for the noise. I hadnt seen those instructs.
```
hledger 1.22.1, linux-x86_64  - ok
hledger 1.21, linux-x86_64 - ok

```
