### ISSUE TITLE
`timedot`/`timeclock` manuals missing from v1.21 and later

### ISSUE THREAD

**Issue by wbadart** [simonmichael/hledger_site#47]
Hey team-

Just noticed that https://hledger.org/1.21/timedot.html gives a blank page. Turning to the network tab in my browser dev tools shows the page is missing:

<img width="265" alt="Screen Shot 2021-08-12 at 08 31 52" src="https://user-images.githubusercontent.com/8717474/129197145-a66e6d90-7443-4b1b-a518-a540e4612a6f.png">

Maybe this issue is more about establishing an informative 404 page; not sure if mdbook has support for this out of the box, but it might help readers navigate out of the above situation in the future.

Thanks!

**Comment by simonmichael** [comment]
Thanks for the report!

It took me quite a while to remember that these were merged into hledger.html as of 1.21. Did a link lead you to this url ?

I agree the 404 page should be improved.

**Comment by simonmichael** [comment]
I have added redirects:
```
# never-existed content that some people try
redir /1.21/journal.html       /hledger.html#journal-format
redir /1.21/csv.html           /hledger.html#csv-format
redir /1.21/timeclock.html     /hledger.html#timeclock-format
redir /1.21/timedot.html       /hledger.html#timedot-format
redir /1.22/journal.html       /hledger.html#journal-format
redir /1.22/csv.html           /hledger.html#csv-format
redir /1.22/timeclock.html     /hledger.html#timeclock-format
redir /1.22/timedot.html       /hledger.html#timedot-format
```
and generic HTTP error pages.

**Comment by wbadart** [comment]
> Did a link lead you to this url ?

Yup, it was the version selection link at the very top of the page.

<img width="499" alt="Screen Shot 2021-08-12 at 18 59 24" src="https://user-images.githubusercontent.com/8717474/129280591-12fa3b53-d070-4d26-962d-d128ca3e0a6e.png">

Redirects are working as expected on my end. Thanks for the quick turnaround!

**Comment by simonmichael** [comment]
Leaving open as redirects are a workaround; in site.js, old journal/csv/timeclock/timedot manuals should link to hledger.html for 1.21+.
