### ISSUE TITLE
Old URLs now leading to 404 errors

### ISSUE THREAD

**Issue by Flimm** [simonmichael/hledger_site#77]
I searched for hledger documentation on Google, and got these results:

![screenshot](https://user-images.githubusercontent.com/355454/224949309-cdfb01f6-a866-4ef1-9c3b-614528b4c9cd.png)

The first result leads to https://hledger.org/MANUAL.html . That URL redirects to https://hledger.org/hledger.html , which redirects in turn to https://hledger.org/1.29/hledger.html , which gives a 404 error.

The second result is https://hledger.org/hledger-ui.html , which redirects to https://hledger.org/1.29/hledger-ui.html , which gives a 404 error.

I think it would be useful if the old URLs redirected to useful pages.

**Comment by simonmichael** [comment]
You're right, thanks for the report. I believe this was a temporary breakage, all seems to be working normally now.

**Comment by simonmichael** [comment]
And sorry for missing this.
