### ISSUE TITLE
there's no actual help on including files

### ISSUE THREAD

**Issue by vigilancetech-com** [simonmichael/hledger_site#86]
at this location:

https://hledger.org/1.30/hledger.html#including-files

there's a link to "include" but it just refers back to this same section that doesn't actually tell how a person might set up a master file that would include all the sub-journal files.

After googling a bit, I still don't know how.

**Comment by vigilancetech-com** [comment]
Or maybe it's just a dead link

**Comment by simonmichael** [comment]
Thanks for the report. I have updated a bunch of links to https://hledger.org/1.30/hledger.html#include-directive , let me know if there is still a problem.

**Comment by vigilancetech-com** [comment]
thanks, that looks much better!
