### ISSUE TITLE
Getting started page says 'see below' but ... there's no below.

### ISSUE THREAD

**Issue by silky** [simonmichael/hledger_site#89]
From: https://hledger.org/start.html

![image](https://github.com/simonmichael/hledger_site/assets/129525/0a9413d1-9058-4142-9ed2-dfdb819b0b5e)

Clearly just a hang-over from some re-organisation, but I can't even guess where this should be referring to; perhaps it can become a link?

**Comment by simonmichael** [comment]
Thanks! I have updated the text.
